// oncology-quest-web/src/components/form/LoginForm.vue
<script setup lang="ts">
import useLogin from "../../hooks/useLogin";

import LabeledFormInput from "./LabeledFormInput.vue"
import LoadingButton from "../LoadingButton.vue"

defineProps<{ onBack: () => void }>()

const {
  loading,
  login,
  loginError,
  password,
  passwordError,
  username,
  usernameError
} = useLogin()

const handleSubmit = (_: Event) => {
  const isError = (usernameError.value || passwordError.value)

  if (!isError) {
    login()
  }
}
</script>

<template>
  <h1>Login to <b><i>Oncology Quest</i></b> below.</h1>
  <form @submit.prevent="handleSubmit">
    <LabeledFormInput
      title="Username"
      name="username"
      type="text"
      :error="usernameError"
      v-model="username"
    />
    <LabeledFormInput
      title="Password"
      name="password"
      type="password"
      :error="passwordError"
      v-model="password"
    />
    <div class="form-error error-label" v-if="loginError">{{ loginError }}</div>
    <LoadingButton :loading="loading" text="Login" />
    <button type="button" class="back" @click="onBack">Back</button>
  </form>
</template>

// bq-web/src/components/LoginForm.tsx
import { useState } from "preact/hooks"

const LoginForm = () => {
  const [username, setUsername] = useState("")
  const [password, setPassword] = useState("")

  const handleSubmit = (e: Event) => {
    e.preventDefault()
    console.log("Login", { username, password })
  }

  return (
    <>
      <h3>Login</h3>
      <form onSubmit={handleSubmit}>
        <input
          type="text"
          placeholder="Username"
          value={username}
          onInput={(e) => setUsername(e.currentTarget.value)}
        />
        <input
          type="password"
          placeholder="Password"
          value={password}
          onInput={(e) => setPassword(e.currentTarget.value)}
        />
        <button type="submit">Login</button>
      </form>
    </>
  )
}

export default LoginForm
