// bq-web/src/components/NoSession.vue
<script setup lang="ts">
import { ref } from "vue"
import LoginForm from "./LoginForm.vue"
import RegisterForm from "./RegisterForm.vue"

enum Views {
  SELECT,
  LOGIN,
  REGISTER
}

const view = ref(Views.SELECT)

const setView = (newView: Views) => {
  view.value = newView;
}
</script>

<template>
  <div>
    <h1>bq</h1>
    <div class="form-container">
      <div v-if="view === Views.SELECT">
        <button @click="setView(Views.LOGIN)">Login</button>
        <button @click="setView(Views.REGISTER)">Register</button>
        <button disabled>Reset Password</button>
      </div>
      <div v-else-if="view === Views.LOGIN">
        <LoginForm />
        <button @click="setView(Views.SELECT)">Back</button>
      </div>
      <div v-else-if="view === Views.REGISTER">
        <RegisterForm />
        <button @click="setView(Views.SELECT)">Back</button>
      </div>
    </div>
  </div>
</template>

// bq-web/src/components/NoSession.tsx
import { useState } from "preact/hooks"
import LoginForm from "./LoginForm"
import RegisterForm from "./RegisterForm"

enum Views {
  SELECT,
  LOGIN,
  REGISTER
}

const NoSession = () => {
  const [view, setView] = useState(Views.SELECT)

  const renderView = () => {
    switch (view) {
      case Views.SELECT:
        return (
          <>
            <button onClick={() => setView(Views.LOGIN)}>Login</button>
            <button onClick={() => setView(Views.REGISTER)}>Register</button>
            <button disabled>Reset Password</button>
          </>
        )
      case Views.LOGIN:
        return (
          <>
            <LoginForm />
            <button onClick={() => setView(Views.SELECT)}>Back</button> 
          </>
        )
      case Views.REGISTER:
        return (
          <>
            <RegisterForm />
            <button onClick={() => setView(Views.SELECT)}>Back</button> 
          </>
        )
    }
  }

  return (
    <div>
      <h1>bq</h1>
      <div className="form-container">
        {renderView()}
      </div>
    </div>
  )
}

export default NoSession
