// bq-web/src/components/RegisterForm.vue
<script setup lang="ts">
import { ref } from "vue";
import { API_ENDPOINT } from "../utility";
import useValidateUsername from "../hooks/useValidateUsername"
import useValidateName from "../hooks/useValidateName";
import useValidateEmail from "../hooks/useValidateEmail";
import useValidateConfirmedPassword from "../hooks/useValidateConfirmedPassword";

const { username, usernameError } = useValidateUsername()
const { name, nameError } = useValidateName()
const { email, emailError } = useValidateEmail()
const {
  password,
  passwordError,
  confirmedPassword,
  confirmedPasswordError 
} = useValidateConfirmedPassword()

const message = ref("")
const serverError = ref("")

const createUser = async () => {
  try {
    const response = await fetch(`${API_ENDPOINT}/api/user/create`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        username: username.value,
        name: name.value,
        email: email.value,
        password: password.value
      })
    })

    if (response.status === 201) {
      message.value = "User created successfully."
    }
    else {
      serverError.value = `Received status code ${response.status}`
    }
  }
  catch (error) {
    serverError.value = "Server error. Please try again later."
  }
}

const handleSubmit = (_: Event) => {
  const isError = (usernameError.value || nameError.value || emailError.value || passwordError.value || confirmedPasswordError.value)

  if (!isError) {
    createUser()
  }
}
</script>

<template>
  <h3>Register</h3>
  <form @submit.prevent="handleSubmit">
    <label for="username">Username</label>
    <input type="text" id="username" name="username" v-model="username" required>
    <label for="name">Name</label>
    <input type="text" id="name" name="name" v-model="name" required>
    <label for="email">Email</label>
    <input type="email" id="email" name="email" v-model="email" required>
    <label for="password">Password</label>
    <input type="password" id="password" name="password" v-model="password" required>
    <label for="password-confirm">Confirm Password</label>
    <input type="password" id="password-confirm" name="password-confirm" v-model="confirmedPassword" required>
    <button type="submit">Register</button>
  </form>
  <div>
    <p v-if="usernameError">{{ usernameError }}</p>
    <p v-if="nameError">{{ nameError }}</p>
    <p v-if="emailError">{{ emailError }}</p>
    <p v-if="passwordError">{{ passwordError }}</p>
    <p v-if="confirmedPasswordError">{{ confirmedPasswordError }}</p>
  </div>
  <div>
    <p v-if="serverError">{{ serverError }}</p>
    <p v-else-if="message">{{ message }}</p>
  </div>
</template>

// bq-web/src/components/RegisterForm.tsx
import { useState } from "preact/hooks"
import { API_ENDPOINT } from "../utility"
import useValidateUsername from "../hooks/useValidateUsername"
import useValidateName from "../hooks/useValidateName"
import useValidateEmail from "../hooks/useValidateEmail"
import useValidateConfirmationPassword from "../hooks/useValidateConfirmationPassword"

const RegisterForm = () => {
  const [message, setMessage] = useState("")
  const [serverError, setServerError] = useState("")
  //const [errors, setErrors] = useState({});
  
  const { username, usernameError } = useValidateUsername()
  const { name, nameError } = useValidateName()
  const { email, emailError } = useValidateEmail()
  const {
    password,
    confirmPassword,
    confirmPasswordError
  } = useValidateConfirmationPassword()

  const createUser = async () => {
    try {
      const response = await fetch(`${API_ENDPOINT}/api/user/create`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          username: username.current,
          name: name.current,
          email: email.current,
          password: password.current
        })
      })

      if (response.status === 201) {
        setMessage("User created successfully.")
      }
      else {
        setServerError(`Received status code ${response.status}`)
      }
    }
    catch (error) {
      setServerError("Server error. Please try again later.")
    }
  }

  // const validateForm = () => {
  //   let newErrors: { email?: string, password?: string, username?: string, name?: string } = {}

  //   if (emailError.current) {
  //     newErrors.email = emailError.current
  //   }

  //   if (confirmPassword.current) {
  //     newErrors.password = confirmPassword.current
  //   }

  //   if (usernameError.current) {
  //     newErrors.username = usernameError.current
  //   }
  //   if (nameError.current) {
  //     newErrors.name = nameError.current
  //   }

  //   setErrors(newErrors)
  //   return Object.keys(errors).length === 0
  // }

  const handleSubmit = (e: Event) => {
    e.preventDefault()
    createUser()
  }

  return (
    <>
      <h3>Register</h3>
      <form onSubmit={handleSubmit}>
        <input
          type="text"
          placeholder="Username"
          value={username.current}
          onInput={(e) => username.current = e.currentTarget.value}
        />
        <input
          type="text"
          placeholder="Name"
          value={name.current}
          onInput={(e) => name.current = e.currentTarget.value}
        />
        <input
          type="email"
          placeholder="Email"
          value={email.current}
          onInput={(e) => email.current = e.currentTarget.value}
        />
        <input
          type="password"
          placeholder="Password"
          value={password.current}
          onInput={(e) => password.current = e.currentTarget.value}
        />
        <input
          type="password"
          placeholder="Confirm Password"
          value={confirmPassword.current}
          onInput={(e) => confirmPassword.current = e.currentTarget.value}
        />
        <button type="submit">Register</button>
        {message && <p>{message}</p>}
        <div>
          {serverError && <p>{serverError}</p>}
          {usernameError.current && <p>{usernameError.current}</p>}
          {nameError.current && <p>{nameError.current}</p>}
          {emailError.current && <p>{emailError.current}</p>}
          {confirmPasswordError.current && <p>{confirmPasswordError.current}</p>}
        </div>
      </form>
    </>
  )
}

export default RegisterForm
