// bq-web/src/components/App.tsx
import useApiConnection from "../hooks/useApiConnection"
import SessionContext from "../contexts/SessionContext"
import AdminDashboard from "./AdminDashboard"
import Dashboard from "./Dashboard"
import NoSession from "./NoSession"

const App = () => {
  let { connectionError, loading, session, setSession } = useApiConnection()

  if (loading) {
    return (
      <main>
        <h1>Loading...</h1>
      </main>
    )
  }

  if (connectionError) {
    return (
      <main>
        <h1>Connection Error</h1>
      </main>
    )
  }

  return (
    <main>
      <SessionContext.Provider value={{ session, setSession }}>
        {session ? (
          session.user.isAdmin ? (
            <AdminDashboard />
          ) : (
            <Dashboard />
          )
        ) : (
          <NoSession />
        )}
      </SessionContext.Provider>
    </main>
  )
}

export default App

// bq-web/src/App.vue
<script setup lang="ts">
import useApiConnection from "./hooks/useApiConnection"
import NoSession from "./components/NoSession.vue"

const { session, loading, connectionError } = useApiConnection()
</script>

<template>
  <main>
    <div v-if="loading" id="loading-wrapper">
      <h1>Loading...</h1>
    </div>
    <div v-else-if="connectionError" id="connection-error-wrapper">
      <h1>Connection Error</h1>
    </div>
    <div v-else>
      <NoSession v-if="!session" />
    </div>
  </main>
</template>

<style scoped>
</style>
